# Generated by Django 2.1.5 on 2019-01-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racelist',
            name='description',
            field=models.TextField(),
        ),
    ]
