# Generated by Django 2.1.5 on 2019-01-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy', '0004_auto_20190123_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[(1, ''), (2, 'Mały'), (3, 'Średni'), (4, 'Duży'), (5, 'Bardzo duży')], max_length=128)),
                ('care', models.CharField(choices=[(1, ''), (2, 'Łatwa'), (3, 'Średnia'), (4, 'Trudna')], max_length=128)),
                ('activity', models.CharField(choices=[(1, ''), (2, 'Wymaga małej aktywności'), (3, 'Wymaga przeciętnej aktywności'), (4, 'Wymaga dużej aktywności')], max_length=128)),
                ('children', models.CharField(choices=[(1, ''), (2, 'Może wychowywać się z dzieckiem'), (3, 'Nie polecany dla rodziny z dziećmi')], max_length=128)),
                ('character', models.CharField(choices=[(1, ''), (2, 'Uległy'), (3, 'Pośredni'), (4, 'Lubi dominować')], max_length=128)),
                ('live_in_city', models.CharField(choices=[(1, ''), (2, 'Nadaje się do mieszkania w bloku'), (3, 'Może mieszkać w bloku z warunkiem możliwości wybiegu'), (4, 'Tylko dom z ogrodem')], max_length=128)),
                ('salary', models.CharField(choices=[(1, ''), (2, 'Stosunkowo małe'), (3, 'Przeciętne'), (4, 'Duże')], max_length=128)),
                ('training', models.CharField(choices=[(1, ''), (2, 'Szybko i chętnie się uczy'), (3, 'Przeciętne zdolności do uczenia')], max_length=128)),
                ('save', models.CharField(choices=[(1, ''), (2, 'Nie nadaje się'), (3, 'Nadaje się warunkowo'), (4, 'Bardzo nadaje się do roli stróża')], max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='RaceList',
        ),
    ]
