# Generated by Django 2.1.5 on 2019-01-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy', '0006_auto_20190124_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='activity',
            field=models.IntegerField(choices=[(1, ''), (2, 'Mała aktywności'), (3, 'Przeciętna aktywność'), (4, 'Duża aktywności')]),
        ),
    ]
