# Generated by Django 2.1.5 on 2019-01-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy', '0007_auto_20190124_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='save',
            new_name='guard',
        ),
    ]
